function sigma2Torque()
    
    stdDis = 100;
    mi = 300;
    c = (mi*pi^2*1^4)/10.5;
    range = [-100:100];
    
    Trq = c*( log(stdDis./(stdDis-range)) - log(stdDis./(stdDis+range)) );
    
    
    figure;
    plot(range,Trq,'-o');
    grid on
    grid minor
    
    yline(-11,'r','DNA melting (-11 pN·nm)');
    title(['Torque \tau generated by given DNA overwind \sigma']);
    xlabel('DNA overwind \sigma [%]');
    ylabel('Torque \tau [pN·nm]');
end